# Generated by Django 4.1.3 on 2022-12-12 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetoecommerce', '0003_produto_valoranterior'),
        ('cadastro', '0002_adicionai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoecommerce.cor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoecommerce.produto')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoecommerce.tamanho')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Desejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoecommerce.produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
