# Generated by Django 4.1.3 on 2022-12-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('avaliacao', models.TextField()),
                ('star', models.IntegerField()),
                ('id_produto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imagens/')),
                ('nome', models.CharField(max_length=255)),
                ('promocao', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('especiais', models.BooleanField()),
                ('grupoTamanho', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estoque', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=255)),
                ('grupo', models.IntegerField()),
            ],
        ),
    ]
