# Generated by Django 4.1.3 on 2022-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoecommerce', '0002_alter_avaliacao_id_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valoranterior',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
